###
# GET All articles
###
GET http://localhost:3000/api/articles?take=4&skip=2
###
# GET an article by id 
###
GET http://localhost:3000/api/articles/2

###
# POST an article
###
POST http://localhost:3000/api/articles
Content-Type: application/json
authorization :  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMiwiZW1haWwiOiJhbmEzNTQzQGdtYWlsLmNvbSIsImlhdCI6MTY4NDMzNDAwNX0.GqvVVbqC7ADg1h1t2SahN2NqspwgInjeoihMysSkky4

{
  "titre": "Example Article",
  "contenu": "This is the content of the article.",
  "image": "https://example.com/image.jpg",
  "published" : true,
  "utilisateurId": 7,
  "categorieIds": [2,3]
}


###
# UPDATE an article
###
PATCH http://localhost:3000/api/articles
Content-Type: application/json

{
  "id":2,
  "titre": "Example Article",
  "contenu": "This is the content of the article.",
  "image": "https://example.com/image.jpg"
}


###
# DELETE an article
###
DELETE http://localhost:3000/api/articles/1
