###
# GET All categories
###
GET http://localhost:3000/api/categories?take=4&skip=2

###
# GET an categorie by id 
###
GET http://localhost:3000/api/categories/2

###
# POST an categorie
###
POST http://localhost:3000/api/categories
Content-Type: application/json

{
  "nom": "fsdjf",
  "articleIds": [2]
}

###
# UPDATE an categorie
###
PATCH http://localhost:3000/api/categories
Content-Type: application/json

{
    "id":4,
  "nom": "fs33djf"
}

###
# DELETE an categorie
###
DELETE http://localhost:3000/api/categories/4
