###
# GET All categories
###
GET http://localhost:3000/categories?take=4&skip=2

###
# GET an categorie by id 
###
GET http://localhost:3000/categories/1

###
# POST an categorie
###
POST http://localhost:3000/categories
Content-Type: application/json

{
}

###
# UPDATE an categorie
###
PATCH http://localhost:3000/categories
Content-Type: application/json

{
}

###
# DELETE an categorie
###
DELETE http://localhost:3000/categories/1
