###
# GET All commentaire
###
GET http://localhost:3000/commentaires?take=4&skip=2

###
# GET an commentaire by id 
###
GET http://localhost:3000/commentaires/1

###
# POST an commentaire
###
POST http://localhost:3000/commentaires
Content-Type: application/json

{
}

###
# UPDATE an commentaire
###
PATCH http://localhost:3000/commentaires
Content-Type: application/json

{
}

###
# DELETE an commentaire
###
DELETE http://localhost:3000/commentaires/1
