###
# GET All commentaire
###
GET http://localhost:3000/api/utilisateurs?take=1&skip=0

###
# GET a user by id 
###
GET http://localhost:3000/api/utilisateurs/4

###
# POST a user
###
POST http://localhost:3000/signup
Content-Type: application/json

{
    "nom": "anas1",
    "email": "ana3543@gmail.com",
    "password": "123333"
}

# POST a user
###
POST http://localhost:3000/api/utilisateurs
Content-Type: application/json

{
    "nom": "anas1",
    "email": "ana35444d43@gmail.com",
    "password": "123333"
}
###
POST http://localhost:3000/signin
Content-Type: application/json

{
    
    "email": "ana3543@gmail.com",
    "password": "123333"
   
}
###
# UPDATE a user
###
PATCH http://localhost:3000/users
Content-Type: application/json

{
    "id":2,
    "nom": "anas1",
    "email": "anas8@gmail.com",
    "password": "123333",
    "role": "AUTHOR"
}

###
# DELETE a user
###
DELETE http://localhost:3000/api/users/4
